app = "botandwebcombined-bot"
primary_region = "ewr"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile.bot"

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = 120000
    restart_limit = 0

# Health endpoint tested by our scripts
[experimental]
  auto_rollback = true
